name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookflow-backend:latest
      
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookflow-frontend:latest
      
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}
          curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}